consumer/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from consumer.views import customer_login_view, consumer_dashboardview, consumer_registration_formview, \
    consumer_adminview, consumer_signupview, SignedOutView, billView, forgetPassword, changePassword, paybillView, \
    consumerupdateView
from home import views
from home.views import homeview

app_name = "consumer"

urlpatterns = [
    path('customer_login', customer_login_view, name='customer_login'),
    path('consumer_dashboard', consumer_dashboardview, name='consumer_dashboard'),
    path('consumer_registration_form', consumer_registration_formview, name='consumer_registration_form'),
    path('consumer_admin', consumer_adminview, name='consumer_admin'),
    path('consumer_signup', consumer_signupview, name='consumer_signup'),
    # path('consumerlogout', consumerlogoutview, name='consumerlogout'),
    path("signed_out", SignedOutView.as_view(), name="sign_out"),
    path('billView/<str:id>', billView, name='billview'),
    path('paybillView/<str:id>', paybillView, name='paybillview'),
    path('consumerupdate/<str:id>/', consumerupdateView, name="consumerupdate"),

    path('forgetpasswordconsumer', forgetPassword, name="forget-password"),
    path('changepasswordconsumer/<token>/', changePassword, name="change-password"),

    # path('consumer_dashboard', consumer_dashboardview, name='consumer_dashboard'),
    # path('consumer_update/<int:phone>', consumer_updateview, name='consumer_update'),
    # path('delete/<int:id>/', consumer_delete, name='consumer_delete'),

]

employee/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from employee.views import employee_dashboardview, employee_registration_formview, employee_login_view, \
    ConsumerSignedOutView, updateView

app_name = "employee"

urlpatterns = [
    path('employeelogin', employee_login_view, name='employeelogin'),
    path('employee_dashboard', employee_dashboardview, name='employee_dashboard'),
    path('employee_registration_form', employee_registration_formview, name='employee_registration_form'),
    # path('employeelogout', employeelogoutview, name='employeelogout'),
    path("empsigned_out", ConsumerSignedOutView.as_view(), name="empsigned_out"),
    path('update/<str:id>', updateView, name='update'),


]

home/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from consumer.views import *
from home import views
from home.views import *
from newWaterBillingSystem import settings

app_name = "home"

urlpatterns = [
    path('', homeview, name='homepage'),
    path('login', login_request, name='login-page'),
    path('register', registerview, name="register"),

    path('edit', editView, name='edit'),
    path('update/<str:id>', updateView, name='update'),
    path('delete/<str:id>', deleteView, name='delete'),

    path('welcome', welcomeview, name="welcome"),
    path('forgetpassword', forgetPassword, name="forget-password"),
    path('changepassword/<token>/', changePassword, name="change-password"),
    path('logoout', logOut, name="logout"),
    path('alluser', consumerView),
    path('about', aboutview, name="about"),
    path('support', supportview, name="support"),
    path('contact', contactview, name="contact"),
    path('message',consumer_messageView, name="message"),

    path('employeetable', employeeview, name="employeetable"),
    path('employeeedit', employeeeditView, name='employeeedit'),
    path('employeeupdate/<str:id>', employeeupdateView, name='employeeupdate'),
    path('employeedelete/<str:id>', employeedeleteView, name='employeedelete'),

    path('billview', billview, name="billview"),
    path('viewbill/<str:id>', billView, name='viewbill'),


]

newWaterBillingSystem/urls.py
from django.contrib import admin
from django.urls import path, include

import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('', include('home.urls', namespace='homepage')),
    path('consumer/', include('consumer.urls', namespace='consumer-page')),
    path('employee/', include('employee.urls', namespace='employee-page')),
    path('billing/', include('billing.urls', namespace='billing-page')),
]

consumer/models.py
from random import random

from django.db import models

# Create your models here.
class Consumer(models.Model):
    id = models.IntegerField(primary_key=True)
    consumer_id = models.IntegerField()
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    meter_no = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    citizenship = models.CharField(max_length=50)


    def __str__(self):
        return "%s   %s" % (self.consumer_id, self.name)

class Consumer_Profile(models.Model):
    consumer = models.OneToOneField(Consumer, on_delete=models.CASCADE, null=True)
    #consumer_details = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    phone = models.IntegerField()
    password = models.CharField(max_length=50)

    def __str__(self):
        return "%s's profile" % (self.consumer.name)


class PasswordProfile(models.Model):
    user = models.OneToOneField(Consumer, on_delete=models.CASCADE, primary_key=True)
    forget_password_token = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name

consumer/forms.py
from django import forms
from .models import Consumer

class ConsumerForm(forms.ModelForm):
    class Meta:
        model = Consumer
        fields = ('name', 'email', 'phone', 'address')

home/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    print(username, password)
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError('User Does Not Exist')

            if not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')

        return super(UserLoginForm, self).clean(*args, **kwargs)


user = get_user_model()


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')
    email2 = forms.EmailField(label='Confirm Email Address')

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = user
        fields = [
            'username',
            'email',
            'email2',
            'password',
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')

        if email != email2:
            raise forms.ValidationError("Emails Don't Match")

        email_qs = user.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Emails Already In Use")

        return super(UserRegisterForm, self).clean(*args, **kwargs)

consumer/views.py
import uuid

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect, get_object_or_404
import random
from django.views.generic.base import TemplateView
from consumer.forms import ConsumerForm
from consumer.models import Consumer, Consumer_Profile, PasswordProfile
from billing.models import consumerBilling
from consumer.helpers import send_forget_password_mail


# Create your views here.

# def consumer_dashboardview(request):
#     # get the logged-in consumer
#     consumer = Consumer.objects.get(id=request.session['consumer_id'])
#
#     # get all the bill records for the logged-in consumer
#     billing = consumerBilling.objects.filter(consumer_id=consumer.consumer_id)
#
#     context = {
#         'consumer': consumer,
#         'billing': billing,
#     }
#
#     return render(request, 'consumer_dashboard.html', context)

def consumer_dashboardview(request):
    # get the logged-in consumer
    consumer_id = request.session.get('consumer_id')
    consumer = Consumer.objects.get(id=consumer_id)

    # get all the bill records for the logged-in consumer
    billing = consumerBilling.objects.filter(consumer_det=consumer_id)
    unpaidbill = billing.filter(status="unpaid")
    u = 0;
    paidbill = billing.filter(status="paid")
    p = 0;

    for i in unpaidbill:
        u+=1;

    for j in paidbill:
        p+=1;

    success_message = request.session.pop('success_message', None)

    context = {
        'unpaidbill': unpaidbill,
        'paidbill' : paidbill,
        'consumer': consumer,
        'billing': billing,
        'u_count' : u,
        'p_count' : p,
        'success_message': success_message,
    }

    return render(request, 'consumer_dashboard.html', context)


def customer_login_view(request):
    if request.method == "POST":
        print("Hello bivek")
        phone = request.POST.get('phone')
        password = request.POST.get('Cpassword')

        try:
            consumer_profile = Consumer_Profile.objects.get(phone=phone, password=password)
            request.session['consumer_id'] = consumer_profile.consumer.id
            return redirect("/consumer/consumer_dashboard")

        except:
            return render(request, "customer_login.html", context={"message": "invalid username or password"})
        # return render(request, "customer_login.html", context={"message": "invalid username or password"})

    form = AuthenticationForm()
    return render(request=request, template_name="customer_login.html", context={"login_form": form})


def consumer_registration_formview(request):
    if request.method == 'POST':
        consumer_id = request.POST.get("consumer_id")
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        address = request.POST.get("address")
        meter_no = request.POST.get("meter_no")
        type = request.POST.get("type")
        citizenship = request.POST.get("citizenship")

        print(consumer_id)

        Consumer.objects.create(
            consumer_id=consumer_id,
            name=name,
            phone=phone,
            email=email,
            address=address,
            meter_no=meter_no,
            type=type,
            citizenship=citizenship
        )
        # print("user created!")
        request.session['success_message'] = "Task successful."
        return redirect("/welcome")

    return render(request, "consumer_registration_form.html")


def consumer_adminview(request):
    return render(request, "consumer.html")


# def consumer_signupview(request):
#     if request.method == 'POST':
#         phone = request.POST.get('phone')
#         password = request.POST.get('password')
#         c_password = request.POST.get('c_password')
#
#         if password!=c_password:
#             return render(request, "Signup.html", {"message": "password not matching"})
#         # print(f'hellllllllllllloooooooooo{phone}')
#         try:
#             consum = Consumer.objects.get(phone=phone)
#             Consumer_Profile.objects.create(phone=phone, password=password)
#             print(consum.phone)
#             Consumer_Profile.save()
#             # print(consum.email)
#             return redirect('/consumer/customer_login')
#         except:
#             return render(request, "Signup.html",{"message":"Invalid phone number"})
#
#         # if Consumer.objects.get(consumer_id=cid):
#         #     print('Success')
#         #     return render(request, "Signup.html")
#
#
#     return render(request, "Signup.html")

def consumer_signupview(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        c_password = request.POST.get('c_password')

        if password != c_password:
            return render(request, "Signup.html", {"message": "password not matching"})

        try:
            # Get the Consumer object
            consumer = Consumer.objects.get(phone=phone)

            # Create the Consumer_Profile object with the foreign key set to the Consumer object
            consumer_profile = Consumer_Profile(consumerobj=consumer, phone=phone, password=password)
            consumer_profile.save()

            return redirect('/consumer/customer_login')
        except:
            return render(request, "Signup.html", {"message": "Invalid phone number"})

    return render(request, "Signup.html")


# def consumer_updateview(request, phone):
#     consumer = Consumer.objects.get(phone=phone)
#     form = ConsumerForm(request.POST or None, instance=consumer)
#     if form.is_valid():
#         form.save()
#         return redirect('/consumer/consumer_admin')
#     return render(request, '/consumer/consumer_update_form.html', {'consumer_update_form': form})

# def consumer_delete(request, id):
#     pass
# consumer = Consumer.objects.get(id=id)
# if request.method == 'POST':
#     consumer.delete()
#     return redirect('consumer_list')
# return render(request, 'consumer/delete.html', {'consumer': consumer})


# @login_required
# def consumerlogoutview(request):
#     logout(request)
#     return redirect('/customer_login_view')


class SignedOutView(TemplateView):
    template_name = "customer_login.html"

    def get(self, request: HttpRequest):
        logout(request)
        return render(request, self.template_name)


def billview(request):
    billing = consumerBilling.objects.all()
    a = 0

    for i in billing:
        a += 1

    context = {
        'count': a,
        'billing': billing,
    }

    return render(request, 'consumer_dashboard.html', context)


def billView(request, id):
    if request.method == 'POST':
        date = request.POST.get('date')
        invoice_id = request.POST.get('invoice_id')
        consumer_id = request.POST.get('consumer_id')
        consumer_name = request.POST.get('consumer_name')
        previous_unit = request.POST.get('previous_unit')
        current_unit = request.POST.get('current_unit')
        meter_no = request.POST.get('meter_no')
        amount = request.POST.get('amount')
        status = request.POST.get('status')

        billing = consumerBilling(
            date=date,
            id=id,
            invoice_id=invoice_id,
            consumer_id=consumer_id,
            consumer_name=consumer_name,
            previous_unit=previous_unit,
            current_unit=current_unit,
            meter_no=meter_no,
            amount=amount,
            status=status,

        )
        billing.save()
        return redirect('/billview')
    return render(request, 'consumer_dashboard.html')



def changePassword(request, token):
    context = {}
    try:
        profile_obj = PasswordProfile.objects.get(forget_password_token=token)
        context = {'phone': profile_obj.user.phone}
        # print("shut up",profile_obj.user.phone)
        if request.method == 'POST':
            new_password = request.POST.get('password')
            confirm_password = request.POST.get('c_password')
            phone = profile_obj.user.phone
            # print("user phone",phone)
            if phone is None:
                messages.success(request, 'No user found.')
                return redirect(f'/consumer/forgetpasswordconsumer/')

            if new_password != confirm_password:
                messages.success(request, 'password mismatch.')
                return redirect(f'/consumer/forgetpasswordconsumer/')

            user_obj = Consumer_Profile.objects.get(phone=phone)
            user_obj.password=new_password
            # user_obj.set_password(new_password)
            user_obj.save()
            return redirect('/consumer/customer_login')

    except Exception as e:
        print(e)
        print("token problem")

    return render(request, 'change_password.html', context)


# http://127.0.0.1:8000/changepassword/fe930ab0-be5a-433b-b738-82c5bd3d4001/
def forgetPassword(request):
    try:
        if request.method == "POST":
            phone = request.POST.get('phone')
            print(phone)

            if not Consumer_Profile.objects.filter(phone=phone).first().phone:

                messages.success(request, 'No user found with this phone number.')
                return redirect('/consumer/forgetpasswordconsumer')

            # print("hello"+username)
            #
            # user_obj = User.objects.get(username=username)
            # token = str(uuid.uuid4())
            # profile_obj = Profile.objects.get(user=user_obj)

            consumer_profile = get_object_or_404(Consumer, phone=phone)
            phone_obj = Consumer.objects.get(phone=phone)

templates/FAQS.html
<!DOCTYPE html>
<!-- {% load static %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="style.css">

    <title>Support</title>
    <style>
        /*{#button a{#}
        {#    text-decoration: none;#}
        {#    background-color: transparent;#}
        {#}#}*/
    
.bg-body {
    background-color: #A4A4A4;
}

.pageheader {
    background-color: #EAFDFC;
}

.pagefooter {
    background-color: #EAFDFC;
}
        button a{
            text-decoration: none;
            background-color: transparent;
        }
        .loginform input{
            font-size: 14px !important;
            padding: 8px !important;
        }
        .supportmain {
  font-size: 16px; /* Adjust the font size as needed */
}

.supportmain h1 {
  font-size: 24px; /* Adjust the font size as needed */
}

.supportmain button.accordion {
  font-size: 14px; /* Adjust the font size as needed */
}

.supportmain div.panel p {
  font-size: 12px; /* Adjust the font size as needed */
}

.mainbody {
  background-color: #A4A4A4;
}

.supportmain h1 {
  color: #EAFDFC;
}


    </style>
</head>
<body>
    <div class="support bg-body">
        <header class="pageheader">
            <nav class="supportnav flex justify-between">
                <div class="logo">
                    <!-- <a href=""><img src="{% static '/images/logo.png' %}" alt="logo"></a> <!----Website Logo---->
                    <img src="Logo.png" alt="logo">
                </div>
                <ul class="navbar align-center">
                    <li><a href="/about">About Us</a></li> <!----Link to About Us page---->
                    <li><a href="/support">FAQs</a></li> <!----Link to Support page---->
                    <li><a href="/contact">Contact Us</a></li>  <!----Link to Contact Us page---->
                    <li><button class="button-color" name="admin"><a href="/login" style="color: #ffffff;" >
                        Admin Login</a></button></li>   <!----Link to Admin Login page---->
                    <li><button class="button-color" name="c_login"><a href="consumer/customer_login" style="color: #ffffff; ">
                        Customer Login</a></li> <!----Link to Customer Login page---->
                </ul>
            </nav>
        </header>
        <main class="supportmain">
            <h1>Frequently Asked Questions (FAQs)</h1>
            <div class="mainbody">
                <button class="accordion">1. What is a water billing system, and how does it work?</button>
                <div class="panel">
                  <p>A water billing system is a software program that helps water suppliers track and bill customers for
                    the water they use. The system typically uses water meters to measure how much water a customer
                    uses, and then calculates the bill based on the meter readings.
                </p>
                </div>

                <button class="accordion">2. Can I pay my water bill online?</button>
                <div class="panel">
                  <p>Yes, we offer online bill payment options, either through their website (connect IPS) Check with your
                    water supplier to find out if online bill payment is available.</p>
                </div>

                <button class="accordion">3. How do I read my water meter?</button>
                <div class="panel">
                  <p>Water meters typically have a digital or analog display that shows the amount of water that has been
                    used. To read your meter, you will need to locate the display and note the numbers or digits that are
                    displayed</p>
                </div>

                <button class="accordion">4. How can I check for water leaks in my home?</button>
                <div class="panel">
                  <p>To check for water leaks in your home, you can perform a simple test by turning off all water sources
                    and checking your water meter. If the meter is still moving, it may indicate a leak. You can also
                    check for visible leaks, such as dripping faucets or running toilets.
                    </p>
                </div>

                <button class="accordion">5. How often will I receive my water bill?</button>
                <div class="panel">
                  <p>The frequency of water bills varies depending on the different water supplier. And we send bills
                    monthly, while others may send them bi-monthly or quarterly.</p>
                </div>


                <button class="accordion">6. What should I do if I think there is an error on my water bill?</button>
                <div class="panel">
                  <p>If you believe there is an error on your water bill, you should contact your water supplier's customer
                    service department. They can investigate the issue and make any necessary adjustments to your bill.</p>
                </div>

                <button class="accordion">7. What happens if I don't pay my water bill?</button>
                <div class="panel">
                  <p>If you don't pay your water bill, your water supplier may take various actions, such as sending you a
                    reminder notice or disconnecting your water service. It is important to pay your water bill on time to
                    avoid any service interruptions or penalties.
                    </p>
                </div>

                <button class="accordion">8. Can I dispute my water bill if I think it is too high?</button>
                <div class="panel">
                  <p>If you think your water bill is too high, you can contact your water supplier's customer service
                    department to dispute the bill. They can investigate the issue and make any necessary adjustments
                    to your bill.
                </p>
                </div>

                <button class="accordion">9. How do I read my water meter?</button>
                <div class="panel">
                  <p>Water meters typically have a digital or analog display that shows the amount of water that has been
                    used. To read your meter, you will need to locate the display and note the numbers or digits that are
                    displayed.
                </p>
                </div>

            </div>
        </main>
        <footer class="pagefooter">
            <div class="pageend">
                <h3>Company</h3>
                <a href=""><p>About Us</p></a>
                <a href=""><p>Contact Us</p></a>
                <a href=""><p>FAQs</p> </a>
            </div>
            <div class="pageend1">
                <h3>Connect With Us</h3>
                <a href=""><img src="fbbb.png" alt="fb"></a>
                <a href=""><img src="twitter.png" alt="tw"></a>
                <a href=""><img src="instagram.png" alt="inst"></a>
            </div>
        </footer>
        <script>
            var acc = document.getElementsByClassName("accordion");
            var i;

            for (i = 0; i < acc.length; i++) {
                acc[i].addEventListener("click", function() {
                /* Toggle between adding and removing the "active" class,
                to highlight the button that controls the panel */
                this.classList.toggle("active");

                /* Toggle between hiding and showing the active panel */
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
                });
            }
        </script>
</body>
</html>

templates/Paymentbillform.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Water Billing System</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="container">
      <h1 style="text-decoration: underline;">Water Billing System</h1>

      <table id="table">
        <thead>
          <tr>
            <th>SN</th>
            <th>Bill Number</th>
            <th>Date</th>
            <th>meterNo.</th>
            <th>Address</th>
            <th>Previous Unit</th>
            <th>Current Unit</th>
            <th>Total Amount</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>123J</td>
            <td>5/3/2023</td>
            <td>1000</td>
            <td>5 unit</td>
            <td>
              <input type="number" id="prevReading" onchange="calculateTotal()">
            </td>
            <td>
              <input type="number" id="currReading" onchange="calculateTotal()">
            </td>
            <td id="total_amount"></td>
            <td id="action">
              <button class="view-bill-btn">View Bill</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <script src="script.js"></script>
  </body>
</html>

templates/customer_login.html
{#<!DOCTYPE html>#}
{#{% load static %}#}
{#<html lang="en" dir="ltr">#}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <link rel="stylesheet" href="{% static 'css/Login.css' %}">#}
{#    <title></title>#}
{#  </head>#}
{#  <body>#}
{#    <div class="container">#}
{#      <form method="post">#}
{#          {% csrf_token %}#}
{#        <h2>Welcome to our application</h2>#}
{#          <p style="color:#ff0000">{{ message }}</p>#}
{#        <p>Please login to use the platform</p>#}
{#        <label for="phone">Phone</label><br>#}
{#        <input type="text" id="phone" name="phone"><br>#}
{#        <label for="password">Password</label><br>#}
{#        <input type="password" id="password" name="Cpassword"><br>#}
{#          <a class="forgotp" href="/forgetpassword">Forgot Password?</a>#}
{#        <button type="submit" name="button">Login</button>#}
{#        <p>New here?<a href="/consumer/consumer_signup">Sign Up</a></p>#}
{#      </form>#}
{#    </div>#}
{#  </body>#}
{#</html>#}

<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Consumer login</title>
  <!-- <link rel="stylesheet" type="text/css" href="consumerlogin.css"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <style type="text/css">
    *{
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}

.content {
  display: flex;
  align-items: center;
  height: 100vh;
}

.leftimage {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50%;
  height: 100%;
}

.leftimage img {
  height: 100%;
}

.rightcontent {
  width: 50%;
}

form {
  padding: 50px 20px;
  background-color: #f2f2f2;
  width: 100%;
  height: 100vh;
}

.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
}

label {
  display: block;
  margin-bottom: 5px;

}

input[type="email"],
input[type="password"] {
  padding: 10px;
  border-radius: 5px;
  border: none;
  margin-bottom: 10px;
  width: 100%;
  font-size: 18px;
}

.conlogin-btn {
  background-color: #007bff;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  width: 100%;
  font-family: 'Poppins', sans-serif;
  font-size: 18px;
}

.conlogin-btn:hover {
  background-color: #0062cc;
}

.small {
  font-size: small;
}

.text-center {
  text-align: center;
}
  </style>
</head>

<body>
  <div class="content">
    <div class="leftimage">
      <img src="{% static 'images/consumerlogin.jpg' %}" alt="water" width="100%" height="100%">
    </div>
    <div class="rightcontent">
      <form method="POST">
         <a href="{% url "home:homepage" %}">
        <i class="fas fa-arrow-left icon" style="font-size: 24px; color: #007bff; margin-right: 10px;"></i> Back to Home</a>
        {% csrf_token %}
        <h2 class="text-center mb-4">Consumer Login</h2>
        <div class="login-container">
          <div style="width:50%;">
            <p style="color:#ff0000">{{ message }}</p>
            <label for="phone">Phone no.</label>
            <input type="text" id="phone" name="phone" required style="width: 100%; padding: 10px; border-radius: 5px; border: none; margin-bottom: 10px; font-size: 18px;"><br><br>
            <label for="password">Password</label>
            <input type="password" id="password" name="Cpassword" required style="width: 100%; padding: 10px; border-radius: 5px; border: none; margin-bottom: 10px; font-size: 18px;"><br>
            <p class="small mt-2 mb-3 pb-lg-2"><a class="text-muted" href="/consumer/forgetpasswordconsumer">Forgot password?</a></p>
            <div class="pt-1 mb-4">
              <button class="btn btn-primary btn-lg btn-block conlogin-btn" type="submit">Login</button>
            </div>
            <p class="small mb-5 pb-lg-2">Don't have an account? <a class="text-muted" href="/consumer/consumer_signup">Go to Sign up</a></p>
          </div>

        </div>
      </form>
    </div>
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>